/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppProgressRouteImport } from './routes/_authenticated/app.progress'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppParentRouteImport } from './routes/_authenticated/app.parent'
import { Route as AuthenticatedAppInsightsRouteImport } from './routes/_authenticated/app.insights'
import { Route as AuthenticatedAppAchievementsRouteImport } from './routes/_authenticated/app.achievements'
import { Route as AuthenticatedAppGamesIndexRouteImport } from './routes/_authenticated/app.games.index'
import { Route as AuthenticatedAppGamesIdRouteImport } from './routes/_authenticated/app.games.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProgressRoute =
  AuthenticatedAppProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppParentRoute = AuthenticatedAppParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppInsightsRoute =
  AuthenticatedAppInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAchievementsRoute =
  AuthenticatedAppAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppGamesIndexRoute =
  AuthenticatedAppGamesIndexRouteImport.update({
    id: '/games/',
    path: '/games/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppGamesIdRoute = AuthenticatedAppGamesIdRouteImport.update({
  id: '/games/$id',
  path: '/games/$id',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/app/achievements': typeof AuthenticatedAppAchievementsRoute
  '/app/insights': typeof AuthenticatedAppInsightsRoute
  '/app/parent': typeof AuthenticatedAppParentRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/progress': typeof AuthenticatedAppProgressRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/games/$id': typeof AuthenticatedAppGamesIdRoute
  '/app/games/': typeof AuthenticatedAppGamesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/app/achievements': typeof AuthenticatedAppAchievementsRoute
  '/app/insights': typeof AuthenticatedAppInsightsRoute
  '/app/parent': typeof AuthenticatedAppParentRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/progress': typeof AuthenticatedAppProgressRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/games/$id': typeof AuthenticatedAppGamesIdRoute
  '/app/games': typeof AuthenticatedAppGamesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/app/achievements': typeof AuthenticatedAppAchievementsRoute
  '/_authenticated/app/insights': typeof AuthenticatedAppInsightsRoute
  '/_authenticated/app/parent': typeof AuthenticatedAppParentRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/progress': typeof AuthenticatedAppProgressRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/games/$id': typeof AuthenticatedAppGamesIdRoute
  '/_authenticated/app/games/': typeof AuthenticatedAppGamesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/onboarding'
    | '/app/achievements'
    | '/app/insights'
    | '/app/parent'
    | '/app/profile'
    | '/app/progress'
    | '/app/settings'
    | '/app/'
    | '/app/games/$id'
    | '/app/games/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/app/achievements'
    | '/app/insights'
    | '/app/parent'
    | '/app/profile'
    | '/app/progress'
    | '/app/settings'
    | '/app'
    | '/app/games/$id'
    | '/app/games'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/onboarding'
    | '/_authenticated/app/achievements'
    | '/_authenticated/app/insights'
    | '/_authenticated/app/parent'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/progress'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/'
    | '/_authenticated/app/games/$id'
    | '/_authenticated/app/games/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/progress': {
      id: '/_authenticated/app/progress'
      path: '/progress'
      fullPath: '/app/progress'
      preLoaderRoute: typeof AuthenticatedAppProgressRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/parent': {
      id: '/_authenticated/app/parent'
      path: '/parent'
      fullPath: '/app/parent'
      preLoaderRoute: typeof AuthenticatedAppParentRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/insights': {
      id: '/_authenticated/app/insights'
      path: '/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AuthenticatedAppInsightsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/achievements': {
      id: '/_authenticated/app/achievements'
      path: '/achievements'
      fullPath: '/app/achievements'
      preLoaderRoute: typeof AuthenticatedAppAchievementsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/games/': {
      id: '/_authenticated/app/games/'
      path: '/games'
      fullPath: '/app/games/'
      preLoaderRoute: typeof AuthenticatedAppGamesIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/games/$id': {
      id: '/_authenticated/app/games/$id'
      path: '/games/$id'
      fullPath: '/app/games/$id'
      preLoaderRoute: typeof AuthenticatedAppGamesIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAchievementsRoute: typeof AuthenticatedAppAchievementsRoute
  AuthenticatedAppInsightsRoute: typeof AuthenticatedAppInsightsRoute
  AuthenticatedAppParentRoute: typeof AuthenticatedAppParentRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppProgressRoute: typeof AuthenticatedAppProgressRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppGamesIdRoute: typeof AuthenticatedAppGamesIdRoute
  AuthenticatedAppGamesIndexRoute: typeof AuthenticatedAppGamesIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAchievementsRoute: AuthenticatedAppAchievementsRoute,
  AuthenticatedAppInsightsRoute: AuthenticatedAppInsightsRoute,
  AuthenticatedAppParentRoute: AuthenticatedAppParentRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppProgressRoute: AuthenticatedAppProgressRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppGamesIdRoute: AuthenticatedAppGamesIdRoute,
  AuthenticatedAppGamesIndexRoute: AuthenticatedAppGamesIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
